AWSTemplateFormatVersion: '2010-09-09'
Description: Challenge App - The registry resource
Parameters:
  EnvironmentName:
    Type: String
    Default: develop
    Description: A name for the environment that this cloudformation will be part of.
  RegistryName:
    Type: String
    Default: challenge-app
    Description: The name of the repository where application containers will
Resources:
  ECRRegistry:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref 'RegistryName'

# These are the values output by the CloudFormation template. Be careful
# about changing any of them, because of them are exported with specific
# names so that the other task related CF templates can use them.
Outputs:
  ImageUrl:
    Description: The url of the image registry
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RegistryName}"
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'ImageUrl' ] ]
